name: Homework Status Fectcher
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  Fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch the status
        run: |
          python3 main.py
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}